#ifndef CELLINKWIDGETS_GLOBAL_H
#define CELLINKWIDGETS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BUILD_CELLINKWIDGETS)
#  define CELLINKWIDGETS_EXPORT Q_DECL_EXPORT
#else
#  define CELLINKWIDGETS_EXPORT Q_DECL_IMPORT
#endif

#endif // CELLINKWIDGETS_GLOBAL_H
