name: Check code formatting
on:
  pull_request:
    branches: [ master, main, dev, feature/* ]

jobs:
  build:
    name: clang-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code (no submodules)
        uses: actions/checkout@v2
      - name: Check with clang-format
        uses: ./.github/actions/clang-format-lint
